version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-springboot
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cadastrodb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
